module Mihari
  module Mixins
    module Configuration
      #
      # Load config file into hash
      #
      # @param [String] path Path to YAML file
      #
      # @return [Hash]
      #
      def load_config: (String path) -> Hash

      #
      # Validate config schema
      #
      # @param [Hash] config
      #
      def validate_config: (Hash config) -> void

      #
      # Returns a template for config
      #
      # @return [String] A template for config
      #
      def config_template: () -> String

      #
      # Create (blank) config file
      #
      # @param [String] filename
      # @param [Dry::Files] files
      # @param [String] template
      #
      # @return [nil]
      #
      def initialize_config_yaml: (String filename, ?untyped files, ?template: String template) -> nil

      private

      def show_validation_errors: (untyped errors) -> void

      def _load_config: (String path) -> untyped
    end
  end
end
