module Mihari
  module Mixins
    module DisallowedDataValue
      #
      # Normalize a value as a disallowed data value
      #
      # @param [String] value Data value
      #
      # @return [String, Regexp] Normalized value
      #
      def normalize_disallowed_data_value: (String value) -> (String | Regexp)

      #
      # Check whetehr a value is valid format as a disallowed data value
      #
      # @param [String] value Data value
      #
      # @return [Boolean] true if it is valid, otherwise false
      #
      def valid_disallowed_data_value?: (String value) -> bool
    end
  end
end
