module Mihari
  module Mixins
    module ErrorNotification
			#
			# Send an exception notification if there is any error in a block
			#
			# @return [Nil]
			#
			def with_error_notification: () { () -> untyped } -> void
    end
  end
end
