module Mihari
  module Mixins
    module Retriable
      #
      # Retry on error
      #
      # @param [Integer] times
      # @param [Integer] interval
      #
      # @return [nil]
      #
      def retry_on_error: (?times: ::Integer times, ?interval: ::Integer interval) { () -> untyped } -> nil
    end
  end
end
