module Mihari
  module Mixins
    module Rule
      #
      # Load rule into hash
      #
      # @param [String] path_or_id
      #
      # @return [Mihari::Structs::Rule::Rule]
      #
      def load_rule: (String path_or_id) -> Mihari::Structs::Rule::Rule

      #
      # Returns a template for rule
      #
      # @return [String] A template for rule
      #
      def rule_template: () -> String

      #
      # Create (blank) rule file
      #
      # @param [String] filename
      # @param [Dry::Files] files
      # @param [String] template
      #
      # @return [nil]
      #
      def initialize_rule_yaml: (String filename, ?untyped files, ?template: String template) -> nil
    end
  end
end
