PreCommit:
  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true
    required_executable: bundle
    command: ["bundle", "exec", "standardrb"]
    on_warn: fail

  YamlSyntax:
    enabled: true
