Style/HashSyntax:
  EnforcedShorthandSyntax: either
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/BlockLength:
  Max: 150
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 50
require:
  - rubocop-rspec
  - rubocop-yard
