site_name: Mihari

theme:
  name: material

plugins:
  search:
  tags:
    enabled: true
    tags_file: tags.md

nav:
  - Requirements: requirements.md
  - Installation: installation.md
  - Architecture: architecture.md
  - Rule: rule.md
  - Configuration: configuration.md
  - Usage: usage.md
  - Tips:
      - Sidekiq: tips/sidekiq.md
      - Docker: tips/docker.md
      - GitHub Actions: tips/github_actions.md
      - Superset: tips/superset.md
      - Sentry: tips/sentry.md
      - Alternatives: tips/alternatives.md
  - References:
      - Analyzers: analyzers/index.md
      - Enrichers: enrichers/index.md
      - Emitters: emitters/index.md
      - Diagrams: diagrams.md
      - Tags: tags.md
  - Development: dev.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
