module Mihari
  class Alert < ActiveRecord::Base
    attr_accessor title (): String
    attr_accessor description (): String?
    attr_accessor source (): String

    attr_accessor artifacts(): Array[Mihari::Artifact]
    attr_accessor Tags(): Array[Mihari::Tag]

    def self.search: (
      ?artifact_data: String? artifact_data,
      ?description: String? description,
      ?source: String? source,
      ?tag_name: String? tag_name,
      ?title: String? title,
      ?from_at: DateTime? from_at,
      ?to_at: DateTime? to_at,
      ?asn: ::Integer? asn,
      ?dns_record: String? dns_record,
      ?reverse_dns_name: String? reverse_dns_name,
      ?limit: ::Integer limit,
      ?page: ::Integer page
    ) -> Array[Hash[(String | Symbol), untyped]]

    def self.count: (
      ?artifact_data: String? artifact_data,
      ?description: String? description,
      ?source: String? source,
      ?tag_name: String? tag_name,
      ?title: String? title,
      ?from_at: DateTime? from_at,
      ?to_at: DateTime? to_at,
      ?asn: ::Integer? asn,
      ?dns_record: String? dns_record,
      ?reverse_dns_name: String? reverse_dns_name
    ) -> Integer

    private

    def self.build_relation: (
      ?artifact_data: String? artifact_data,
      ?title: String? title,
      ?description: String? description,
      ?source: String? source,
      ?tag_name: String? tag_name,
      ?from_at: DateTime? from_at,
      ?to_at: DateTime? to_at,
      ?asn: ::Integer? asn,
      ?dns_record: String? dns_record,
      ?reverse_dns_name: String? reverse_dns_name
    ) -> Mihari::Alert
  end
end
