module Mihari
  class Alert < ActiveRecord::Base
    attr_accessor title (): String
    attr_accessor description (): String?
    attr_accessor source (): String

    attr_accessor artifacts(): Array[Mihari::Artifact]
    attr_accessor Tags(): Array[Mihari::Tag]

    def self.search: (Mihari::Structs::Alert::SearchFilterWithPagination filter) -> Array[Hash[(String | Symbol), untyped]]

    def self.count: (Mihari::Structs::Alert::SearchFilter filter) -> Integer

    private

    def self.build_relation: (Mihari::Structs::Alert::SearchFilter filter) -> Mihari::Alert
  end
end
