module Mihari
  class ReverseDnsName < ActiveRecord::Base
    attr_accessor name (): String

    #
    # Build reverse DNS names
    #
    # @param [String] ip
    #
    # @return [Array<Mihari::ReverseDnsName>]
    #
    def self.build_by_ip: (String ip) -> Array[Mihari::ReverseDnsName]
  end
end
