module Mihari
  module Emitters
    class MISP < Base

      attr_reader url: String?

      attr_reader api_key: String?


      def initialize: () -> void

      # @return [true, false]
      def valid?: () -> bool

      def emit: (title: String title, artifacts: Array[Mihari::Artifact] artifacts, ?tags: Array[String] tags, **untyped _options) -> void

      private

      def configuration_keys: () -> ::Array["misp_url" | "misp_api_key"]

      def build_attribute: (Mihari::Artifact artifact) -> untyped

      def hash_type: (String value) -> String?

      def to_misp_type: (type: String `type`, value: String value) -> String?

      def url?: () -> bool

      def api_key?: () -> bool

      def ping?: () -> bool
    end
  end
end
