module Mihari
  module Emitters
    class Attachment
      attr_reader data: String
      attr_reader data_type: String

      # extend Dry::Initializer

      def actions: () -> Array[Hash[(String | Symbol), untyped]]

      def vt_link: () -> (nil | { :type => "button", text: "VirusTotal", url: String })

      def urlscan_link: () -> (nil | { :type => "button", text: "urlscan.io", url: String })

      def censys_link: () -> (nil | { :type => "button", text: "Censys", url: String })

      def shodan_link: () -> (nil | { :type => "button", text: "Shodan", url: String })

      # @return [Array]
      def to_a: () -> ::Array[{ text: String, fallback: "VT & urlscan.io links", actions: Array[Hash[(String | Symbol), untyped]] }]

      private

      # @return [String]
      def _urlscan_link: () -> String?

      # @return [String]
      def _vt_link: () -> String?

      def _censys_link: () -> String?

      def _shodan_link: () -> String?

      # @return [String]
      def sha256: () -> String

      # @return [String]
      def defanged_data: () -> String
    end

    class Slack < Base
      SLACK_WEBHOOK_URL_KEY: ::String

      SLACK_CHANNEL_KEY: ::String

      DEFAULT_USERNAME: ::String

      #
      # Slack channel to post
      #
      # @return [String]
      #
      def slack_channel: () -> String

      #
      # Slack webhook URL
      #
      # @return [String]
      #
      def slack_webhook_url: () -> String

      #
      # Check Slack webhook URL is set
      #
      # @return [Boolean]
      #
      def slack_webhook_url?: () -> bool


      def notifier: () -> ::Slack::Notifier

      def valid?: () -> bool

      def to_attachments: (Array[Mihari::Artifact] artifacts) -> Array[Mihari::Emitters::Attachment]

      def to_text: (title: String title, description: String description, ?tags: Array[String] tags) -> String

      def emit: (title: String title, description: String description, artifacts: Array[Mihari::Artifact] artifacts, ?tags: Array[String] tags, **untyped _options) -> void

      private

      def configuration_keys: () -> ::Array["slack_webhook_url"]
    end
  end
end
