module Mihari
  module Emitters
    class TheHive < Base
      attr_reader url: String?

      attr_reader api_key: String?

      attr_reader api_version: String?

      # @return [true, false]
      def valid?: () -> bool

      def emit: (title: untyped title, description: untyped description, artifacts: untyped artifacts, ?tags: untyped tags, **untyped _options) -> (nil | untyped)

      def normalized_api_version: () -> String?

      private

      def configuration_keys: () -> ::Array["thehive_url" | "thehive_api_key"]

      def api: () -> untyped

      # @return [true, false]
      def url?: () -> bool

      # @return [true, false]
      def api_key?: () -> bool

      def ping?: () -> bool
    end
  end
end
