module Mihari
  module CLI
    class Analyzer < Base
      include Mihari::Commands::BinaryEdge

      include Mihari::Commands::Censys

      include Mihari::Commands::CIRCL

      include Mihari::Commands::Crtsh

      include Mihari::Commands::DNPedia

      include Mihari::Commands::DNSTwister

      include Mihari::Commands::Feed

      include Mihari::Commands::GreyNoise

      include Mihari::Commands::JSON

      include Mihari::Commands::Onyphe

      include Mihari::Commands::OTX

      include Mihari::Commands::PassiveTotal

      include Mihari::Commands::Pulsedive

      include Mihari::Commands::SecurityTrails

      include Mihari::Commands::Shodan

      include Mihari::Commands::Spyse

      include Mihari::Commands::Urlscan

      include Mihari::Commands::VirusTotal

      include Mihari::Commands::ZoomEye
    end
  end
end
