module Mihari
  module Feed
    class Parser
      attr_reader data: Array[Hash] | Array[Array[String]]

      def initialize: (Array[Hash] | Array[Array[String]] data) -> void

      def parse: (String selector) -> Array[String]
    end
  end
end
