module Mihari
  module Analyzers
    class BinaryEdge < Base

      attr_reader query: String
      attr_reader title: String
      attr_reader description: String
      attr_reader tags: Array[String]

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      PAGE_SIZE: ::Integer

      def search_with_page: (String query, ?page: ::Integer page) -> Hash[(String | Symbol), untyped]

      def search: () -> Array[Hash[(String | Symbol), untyped]]

      def configuration_keys: () -> ::Array["binaryedge_api_key"]

      def api: () -> untyped
    end
  end
end
