module Mihari
  module Analyzers
    class Crtsh < Base
      attr_reader query: String
      attr_reader title: String
      attr_reader description: String
      attr_reader tags: Array[String]
      attr_reader exclude_expired: bool

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def api: () -> untyped

      def search: () -> Array[Hash[(String | Symbol), untyped]]
    end
  end
end
