module Mihari
  module Analyzers
    class DNPedia < Base
      attr_reader query: String

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def api: () -> untyped

      def search: () -> Array[Mihari::Artifact]
    end
  end
end
