module Mihari
  module Analyzers
    class DNSTwister < Base
      include Mixins::Refang

      attr_reader query: String

      attr_reader type: String

      def initialize: (*untyped args, **untyped kwargs) -> void

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def valid_type?: () -> bool

      def api: () -> untyped

      def resolvable?: (String domain) -> bool

      def search: () -> Array[String]
    end
  end
end
