module Mihari
  module Analyzers
    class OTX < Base
      include Mixins::Refang

      attr_reader query: String

      attr_reader type: String?

      attr_reader api_key: String?

      def initialize: (*untyped args, **untyped kwargs) -> void

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def configuration_keys: () -> ::Array["otx_api_key"]

      def domain_client: () -> untyped

      def ip_client: () -> untyped

      def valid_type?: () -> bool

      def search: () -> Array[String]

      def domain_search: () -> Array[String]

      def ip_search: () -> Array[String]
    end
  end
end
