module Mihari
  module Analyzers
    class SecurityTrails < Base
      include Mixins::Refang

      attr_reader query: String

      attr_reader type: String

      def initialize: (*untyped args, **untyped kwargs) -> void

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def configuration_keys: () -> ::Array["securitytrails_api_key"]

      def api: () -> untyped

      def valid_type?: () -> bool

      def search: () -> Array[String]

      def domain_search: () -> Array[String]

      def ip_search: () -> Array[Mihari::Artifact]

      def mail_search: () -> Array[Mihari::Artifact]
    end
  end
end
