SUPPORTED_DATA_TYPES: untyped

module Mihari
  module Analyzers
    class Urlscan < Base
      attr_reader query: String

      attr_reader allowed_data_types: Array[String]

      attr_reader interval: ::Integer

      attr_reader api_key: String?

      def initialize: (*untyped args, **untyped kwargs) -> void

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def configuration_keys: () -> ::Array["urlscan_api_key"]

      def api: () -> untyped

      def search_with_search_after: (search_after: String?) -> Array[Hash[(String | Symbol), untyped]]

      def search: () -> Array[Mihari::Structs::Urlscan::Response]

      def valid_alllowed_data_types?: () -> bool
    end
  end
end
