module Mihari
  module Analyzers
    class VirusTotalIntelligence < Base
      attr_reader query: String
      attr_reader title: String
      attr_reader description: String
      attr_reader tags: Array[String]

      def initialize: (*untyped args, **untyped kwargs) -> void

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      def configuration_keys: () -> ::Array["virustotal_api_key"]

      #
      # VT API
      #
      # @return [::VirusTotal::API]
      #
      def api: () -> VirusTotal::API

      #
      # Search with cursor
      #
      # @return [Array<Mihari::Structs::VirusTotalIntelligence::Response>]
      #
      def search_witgh_cursor: () -> Array<Mihari::Structs::VirusTotalIntelligence::Response>
    end
  end
end
