module Mihari
  module Analyzers
    class ZoomEye < Base
      attr_reader query: String
      attr_reader title: String
      attr_reader description: String
      attr_reader tags: Array[String]
      attr_reader type: String

      def artifacts: () -> (Array[String] | Array[Mihari::Artifact])

      private

      PAGE_SIZE: ::Integer

      def valid_type?: () -> bool

      def configuration_keys: () -> ::Array["zoomeye_api_key"]

      def api: () -> untyped

      def convert_responses: (Array[Hash[(String | Symbol), untyped]] responses) -> Array[String]

      def _host_search: (String query, ?page: ::Integer page) -> (Hash[(String | Symbol), untyped] | nil)

      def host_search: () -> Array[String]

      def _web_search: (String query, ?page: ::Integer page) -> (Hash[(String | Symbol), untyped] | nil)

      def web_search: () -> Array[String]
    end
  end
end
