#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "mihari"

begin
  input = ARGV.first || gets
  Mihari::CLI.start input
rescue ArgumentError, Mihari::Error => e
  puts e
end
