module Mihari
  module Structs
    module Censys
      class AutonomousSystem
        attr_reader asn: Integer

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Censys::AutonomousSystem
      end

      class Location
        attr_reader country: String
        attr_reader country_code: String

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Censys::Location
      end

      class Hit
        attr_reader ip: String
        attr_reader location: Mihari::Structs::Censys::Location
        attr_reader autonomous_system: Mihari::Structs::Censys::AutonomousSystem

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Censys::Hit
      end

      class Links
        attr_reader next: String
        attr_reader prev: String

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Censys::Links
      end

      class Result
        attr_reader query: String
        attr_reader total: Integer
        attr_reader hits: Array[Mihari::Structs::Censys::Hit]
        attr_reader links: Mihari::Structs::Censys::Links

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Censys::Result
      end

      class Response
        attr_reader code: Integer
        attr_reader status: String
        attr_reader result: Mihari::Structs::Censys::Result

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Censys::Response
      end
    end
  end
end
