module Mihari
  module Structs
    module GooglePublicDNS
      INT_TYPE_TO_TYPE: { 1 => "A", 2 => "NS", 5 => "CNAME", 16 => "TXT", 28 => "AAAA" }

      class Answer < Dry::Struct
			  attr_reader name: String
        attr_reader data: String
        attr_reader resource_type: String

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::GooglePublicDNS::Answer
      end

      class Response < Dry::Struct
        attr_reader answers: Array[Mihari::Structs::GooglePublicDNS::Answer]

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::GooglePublicDNS::Response
      end
    end
  end
end