module Mihari
  module Structs
    module GreyNoise
      class Metadata < Dry::Struct
        attr_reader country: String
        attr_reader country_code: String
        attr_reader asn: String

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) ->  Mihari::Structs::GreyNoise::Metadata
      end

      class Datum < Dry::Struct
        attr_reader ip: String
        attr_reader metadata: Mihari::Structs::GreyNoise::Metadata

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::GreyNoise::Datum
      end

      class Response < Dry::Struct
        attr_reader complete: Boolean
        attr_reader count: Integer
        attr_reader data: Array[Mihari::Structs::GreyNoise::Danum]
        attr_reader message: String
        attr_reader query: String

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::GreyNoise::Response
      end
    end
  end
end
