module Mihari
  module Structs
    module IPInfo
      class Response
        attr_reader ip: String
        attr_reader hostname: String?
        attr_reader loc: String
        attr_reader country_code: String
        attr_reader asn: String

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::IPInfo::Response

        def to_hash: () -> Hash[(String | Symbol), untyped]
      end
    end
  end
end
