module Mihari
  module Structs
    module Rule
      class SearchFilter < Dry::Struct
      end

      class SearchFilterWithPagination < SearchFilter
        def without_pagination: () -> SearchFilter
      end

      class Rule
        attr_reader data: Hash

        attr_reader errors: Array[untypes]

        def initialize: (Hash data) -> void

        #
        # @return [Boolean]
        #
        def errors?: () -> (bool)

        #
        # @return [Array[String]]
        #
        def error_messages: () -> (Array[String])

        def validate: () -> void

        def validate!: () -> void

        def []: (untyped key) -> untyped

        #
        # @return [String]
        #
        def id: () -> String

        #
        # @return [String]
        #
        def title: () -> String

        #
        # @return [String]
        #
        def description: () -> String

        #
        # @return [Mihari::Rule]
        #
        def to_model: () -> Mihari::Rule
      end
    end
  end
end
