module Mihari
  module Structs
    module Shodan
      class Location
        attr_reader country_code: String?
        attr_reader country_name: String?

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Shodan::Location
      end

      class Match
        attr_reader asn: String?
        attr_reader hostnames: Array[String]
        attr_reader location: Mihari::Structs::Shodan::Location
        attr_reader domains: Array[String]
        attr_reader ip_str: String
        attr_reader port: Integer

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Shodan::Match
      end

      class Result
        attr_reader matches: Array[Mihari::Structs::Shodan::Match]
        attr_reader total: Integer

        def self.from_dynamic!: (Hash[(String | Symbol), untyped] d) -> Mihari::Structs::Shodan::Result
      end
    end
  end
end
