module Mihari
  module Types
    Int: ::Integer

    Nil: nil

    Hash: Hash[(String | Symbol), untyped]

    String: ::String

    Double: (::Float | ::Integer)

    DataTypes: Array[String]

    AnalyzerTypes: Array[String]

    FeedHttpRequestMethods: Array[String]

    FeedHttpRequestPayloadTypes: Array[String]
  end
end
