module Mihari
  module Enrichers
    class GooglePublicDNS < Base
      # @return [Boolean]
      def valid?: () -> true

      #
      # Query Google Public DNS
      #
      # @param [String] name
      # @param [String] resource_type
      #
      # @return [Mihari::Structs::Shodan::GooglePublicDNS::Response, nil]
      #
      def self.query: (String name, String resource_type) -> Mihari::Structs::Shodan::GooglePublicDNS::Response?
    end
  end
end