module Mihari
  module Notifiers
    class Slack < Base
      SLACK_WEBHOOK_URL_KEY: ::String

      SLACK_CHANNEL_KEY: ::String

      DEFAULT_USERNAME: ::String

      #
      # Slack channel to post
      #
      # @return [String]
      #
      def slack_channel: () -> String

      #
      # Slack webhook URL
      #
      # @return [String]
      #
      def slack_webhook_url: () -> String

      #
      # Check Slack webhook URL is set
      #
      # @return [Boolean]
      #
      def slack_webhook_url?: () -> bool

      #
      # Check Slack webhook URL is set. Alias of #slack_webhook_url?.
      #
      # @return [Boolean]
      #
      def valid?: () -> bool

      #
      # Send notification to Slack
      #
      # @param [String] text
      # @param [Array<Hash>] attachments
      # @param [Boolean] mrkdwn
      #
      # @return [nil]
      #
      def notify: (text: String text, ?attachments: Array[Hash[(String | Symbol), untyped]] attachments, ?mrkdwn: bool mrkdwn) -> untyped
    end
  end
end
